input_number:
  set_smartpool_phmin:
    name: pHMin
    initial: 7.0
    min: 0
    max: 14
    step: 0.1
    mode: slider
  set_smartpool_phmax:
    name: pHMax
    initial: 8.0
    min: 0
    max: 14
    step: 0.1
    mode: slider
  set_smartpool_redox:
    name: Redox
    initial: 700
    min: 300
    max: 800
    step: 5
    mode: slider
  set_smartpool_hydrolysis:
    name: Hydrolysis
    initial: 10
    min: 0
    max: 30
    step: 1
    mode: slider

mqtt:
  switch:
    - unique_id: "pool_pump_switch"
      name: "Pool Pump Switch"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPFiltration"
      state_topic: "stat/SmartPool/NPFILTRATION"
      value_template:  >- 
        {% set values = { 'OFF':'0', 'ON':'1' } %}
        {{ values[value_json["NPFiltration"]] if value_json["NPFiltration"] in values.keys() and states('select.pool_pump_mode') == 'Manual' else '' }}
      payload_on: "1"
      payload_off: "0"

    - unique_id: "pool_lights"
      name: "Pool Lights"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPLight"
      state_topic: "stat/SmartPool/NPLIGHT"
      value_template: >- 
        {% set values = { 'OFF':'0', 'ON':'1' } %}
        {{ values[value_json["NPLight"]] if value_json["NPLight"] in values.keys() else '99' }}
      payload_on: "1"
      payload_off: "0"

  select:
    - unique_id: "pool_pump_mode"
      name: "Pool Pump Mode"
      command_topic: "cmnd/SmartPool/NPFiltrationMode"
      state_topic: "stat/SmartPool/NPFILTRATIONMODE"
      command_template: >- 
        {% set values = { 'Manual':'0', 'Auto':'1', 'Heating':'2', 'Smart':'3', 'Intelligent':'4' } %}
        {{ values[value] if value in values.keys() else '99' }}
      value_template: >-
        {% if value_json.NPFiltrationmode == '' %}
          Intelligent
        {%- else -%}
          {{ value_json.NPFiltrationmode }}
        {%- endif -%}
      options:
        - Manual
        - Auto
        - Heating
        - Smart
        - Intelligent

    - unique_id: "pool_pump_speed"
      name: "Pool Pump Speed"
      command_topic: "cmnd/SmartPool/NPFiltration"
      state_topic: "stat/SmartPool/NPFILTRATION"
      command_template: >-
        {% set values = { 'Slow':'1', 'Medium':'2', 'Fast':'3' } %}
        {% if is_state('switch.pool_pump_switch', 'on') %}
          {{ '1 ' + values[value] if value in values.keys() else '99' }}
        {% elif is_state('switch.pool_pump_switch', 'off') %}
          {{ '0 ' + values[value] if value in values.keys() else '99' }}
        {% endif %}
      value_template: >-
        {% set values = { '1':'Slow', '2':'Medium', '3':'Fast' } %}
        {{ values[value_json["Speed"]] if value_json["Speed"] in values.keys() else '99' }}
      options:
        - Slow
        - Medium
        - Fast
        
  - platform: template
    sensors:
      pump_mode:
        friendly_name: "Mode"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_filtration_mode', '0') %}
            Manual
          {% elif is_state('sensor.smartpool_neopool_filtration_mode', '1') %}
            Auto
          {% elif is_state('sensor.smartpool_neopool_filtration_mode', '2') %}
            Heating
          {% elif is_state('sensor.smartpool_neopool_filtration_mode', '3') %}
            Smart
          {% elif is_state('sensor.smartpool_neopool_filtration_mode', '4') %}
            Intelligent
          {% elif is_state('sensor.smartpool_neopool_filtration_mode', '13') %}
            Backwash
          {% endif %}

      pump_state:
        friendly_name: "State"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_filtration_state', '0') %}
            Off
          {% elif is_state('sensor.smartpool_neopool_filtration_state', '1') %}
            On
          {% endif %}

      pump_speed:
        friendly_name: "Speed"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_filtration_speed', '1') %}
            Slow
          {% elif is_state('sensor.smartpool_neopool_filtration_speed', '2') %}
            Medium
          {% elif is_state('sensor.smartpool_neopool_filtration_speed', '3') %}
            Fast
          {% endif %}

      heating:
        friendly_name: "Pool Heatpump"
        value_template: >- 
          {% if '1' in states('sensor.smartpool_neopool_relay_aux').split(",")[3].split("]")[0] %}                
            On
          {% else %}
            Off
          {% endif %}

      hydrolysis_boost:
        friendly_name: "Shock"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_hydrolysis_boost', '0') %}
            Off
          {% elif is_state('sensor.smartpool_neopool_hydrolysis_boost', '1') %}
            On
          {% else %}
            state.sensor.smartpool_neopool_hydrolysis_boost
          {% endif %}

      hydrolysis_cover:
        friendly_name: "Cover"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_hydrolysis_cover', '0') %}
            Off
          {% elif is_state('sensor.smartpool_neopool_hydrolysis_cover', '1') %}
            On
          {% else %}
            state.sensor.smartpool_neopool_hydrolysis_cover
          {% endif %}

      hydrolysis_low:
        friendly_name: "Low Alarm"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_hydrolysis_low', '0') %}
            Off
          {% elif is_state('sensor.smartpool_neopool_hydrolysis_low', '1') %}
            On
          {% else %}
            state.sensor.smartpool_neopool_hydrolysis_low
          {% endif %}

      hydrolysis_production:
        friendly_name: "Production"
        value_template: "{{ states('sensor.smartpool_neopool_hydrolysis_data') + ' ' + states('sensor.smartpool_neopool_hydrolysis_unit') }}"

      hydrolysis_state:
        friendly_name: "State"
        value_template: >-
          {% if is_state('sensor.smartpool_neopool_hydrolysis_state', 'Pol1') %}
            Polarity 1
          {% elif is_state('sensor.smartpool_neopool_hydrolysis_state', 'Pol2') %}
            Polarity 2
          {% elif is_state('sensor.smartpool_neopool_hydrolysis_state', 'Flow') %}
            No water flow
          {% else %}
            Off
          {% endif %}
